### ISSUE TITLE
Enhancement ideas

### ISSUE THREAD

**Issue by 3arn0wl** [ubports/address-book-service#3]
Hi
I have a number of enhancement ideas, for more intelligent contacts and communications.
If contacts' databases were linked, then as and when data was updated, it would be updated to all the contacts that had that field. Fields could be edited depending on the relationship: business, personal, family...

It would be good to link to the person's preferred method of communication - text or email / voice or VoIP. Also it might be nice to have the option to control where calls are sent from and received depending on time and location. The option to switch off the communications altogether might also be useful.

On the Index screen, it might be good to have "Frequent communications from this location" along with the "Favourite" and "All" options

Obviously, integrating Nextcloud contacts would be really powerful too.

I've done an .odp with more details. If you're interested:  https://3arn0wl.hopto.org/index.php/s/xnNJPoDp25gqQ2N

**Comment by UniversalSuperBox** [comment]
Hi @3arn0wl, thanks for your report. And sorry about the long wait for a response!

I believe you have good ideas for the direction of the address book service. However, no contributor will be able to act on this issue report in a way that it can be closed. There are simply too many tasks here.

If you believe some of these requests are still relevant, please file them on the repository where you feel is best: for example, dialing from different numbers based on the time of day could be added to the dialer app's repository. Otherwise, putting everything in ubports/ubuntu-touch is a safe bet.

Thanks once again for your report. I hope to see more, targeted reports in the near future!
